<a href="https://colab.research.google.com/github/TanviPawar09/Power-BI-Dashboard/blob/main/Student_Depression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
df=pd.read_csv("/content/Student Depression Dataset.csv")
df

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [9]:
df.isnull().sum()

id                                       0
Gender                                   0
Age                                      0
City                                     0
Profession                               0
Academic Pressure                        0
Work Pressure                            0
CGPA                                     0
Study Satisfaction                       0
Job Satisfaction                         0
Sleep Duration                           0
Dietary Habits                           0
Degree                                   0
Have you ever had suicidal thoughts ?    0
Work/Study Hours                         0
Financial Stress                         3
Family History of Mental Illness         0
Depression                               0
dtype: int64

In [10]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
27896    False
27897    False
27898    False
27899    False
27900    False
Length: 27901, dtype: bool

In [11]:
df.info

<bound method DataFrame.info of            id  Gender   Age           City Profession  Academic Pressure  \
0           2    Male  33.0  Visakhapatnam    Student                5.0
1           8  Female  24.0      Bangalore    Student                2.0
2          26    Male  31.0       Srinagar    Student                3.0
3          30  Female  28.0       Varanasi    Student                3.0
4          32  Female  25.0         Jaipur    Student                4.0
...       ...     ...   ...            ...        ...                ...
27896  140685  Female  27.0          Surat    Student                5.0
27897  140686    Male  27.0       Ludhiana    Student                2.0
27898  140689    Male  31.0      Faridabad    Student                3.0
27899  140690  Female  18.0       Ludhiana    Student                5.0
27900  140699    Male  27.0          Patna    Student                4.0

       Work Pressure  CGPA  Study Satisfaction  Job Satisfaction  \
0                0.0  8.97                 2.0               0.0
1                0.0  5.90                 5.0               0.0
2                0.0  7.03                 5.0               0.0
3                0.0  5.59                 2.0               0.0
4                0.0  8.13                 3.0               0.0
...              ...   ...                 ...               ...
27896            0.0  5.75                 5.0               0.0
27897            0.0  9.40                 3.0               0.0
27898            0.0  6.61                 4.0               0.0
27899            0.0  6.88                 2.0               0.0
27900            0.0  9.24                 1.0               0.0

          Sleep Duration Dietary Habits    Degree  \
0              5-6 hours        Healthy   B.Pharm
1              5-6 hours       Moderate       BSc
2      Less than 5 hours        Healthy        BA
3              7-8 hours       Moderate       BCA
4              5-6 hours       Moderate    M.Tech
...                  ...            ...       ...
27896          5-6 hours      Unhealthy  Class 12
27897  Less than 5 hours        Healthy       MSc
27898          5-6 hours      Unhealthy        MD
27899  Less than 5 hours        Healthy  Class 12
27900  Less than 5 hours        Healthy       BCA

      Have you ever had suicidal thoughts ?  Work/Study Hours  \
0                                       Yes               3.0
1                                        No               3.0
2                                        No               9.0
3                                       Yes               4.0
4                                       Yes               1.0
...                                     ...               ...
27896                                   Yes               7.0
27897                                    No               0.0
27898                                    No              12.0
27899                                   Yes              10.0
27900                                   Yes               2.0

       Financial Stress Family History of Mental Illness  Depression
0                   1.0                               No           1
1                   2.0                              Yes           0
2                   1.0                              Yes           0
3                   5.0                              Yes           1
4                   1.0                               No           0
...                 ...                              ...         ...
27896               1.0                              Yes           0
27897               3.0                              Yes           0
27898               2.0                               No           0
27899               5.0                               No           1
27900               3.0                              Yes           1

[27901 rows x 18 columns]>